name: ci-workflow
on:
  pull_request:
    branches:
      - main

jobs:
  CI-workflow-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4
    
      - name: build app
        run: mvn clean package
        shell: bash 

      - name: test the app
        run: "mvn test"
        shell: bash

